### ISSUE TITLE
Increase default expire interval for ap4rc passwords

### ISSUE THREAD

**Issue by lrupp** [darix/ap4rc#1]
In your default configuration, you have:
```
$config['ap4rc_expire_interval'] = "2 MONTH";
$config['ap4rc_warning_interval'] = "1 WEEK";
```

Could you please explain, why such (especially: short) intervals are needed?

I like to vote for longer times, as [latest studies](https://www.cs.unc.edu/~fabian/papers/PasswordExpire.pdf) show that it's even better for security to allow users to have longer intervals for changing their own, memorized secrets - which are seen as much more insecure than generated ones. 

Even the [NIST guidelines](https://pages.nist.gov/800-63-3/sp800-63-3.html) removed the need for regular password (memorized secrets) changes since a while:  "Users should change their password if they are compromised (or suspected to have been compromised)." 

Enforcing a change of a generated application password in such short time frames looks contra-productive in this regard, but I agree that it can be an additional option for certain circumstances. 

But your defaults will result in additional load for people inside support and confuse people. Just think about customers, who just notice that their application does not allow them to log in any longer. They will open support tickets just because they did not visit the WebUI. 

Therefor I like to suggest longer default expiry times - or even allow to set the expiry time to '0', to disable expiry times completely.

**Comment by jdsn** [comment]
It is just a default. Please change it to you your preferred value.
To disable it, set the expiry to a looooong time e.g. "1000 YEAR".
